version: '3.5'

services:
  ui:
    image: node:16.20.0
    working_dir: /app
    command: npm start
    #command: sleep infinity
    user: node
    volumes:
      - ./:/app
    ports:
      - 8083:8080
      #- 1300:1300
      #- 3001:3001

  prod:
    image: m3ng9i/ran
    volumes:
      - ./dist:/web
    ports:
      - 8081:8080
